---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.18.9, namelong: vg-suricata-01.local, nameshort: vg-suricata-01 }
  - { ip: 192.168.18.10, namelong: vg-suricata-02.local, nameshort: vg-suricata-02 }
  - { ip: 192.168.18.11, namelong: vg-suricata-03.local, nameshort: vg-suricata-03 }
  - { ip: 192.168.18.12, namelong: vg-suricata-04.local, nameshort: vg-suricata-04 }
  when: add_host_entries
